# Generated by Django 3.1.7 on 2021-05-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='post', to='blogdjango.Tag'),
        ),
    ]
